
all_files(
	[reform,
	 ASIS/absindex,
	 ASIS/analyser,
	 ASIS/annotate,
	 ASIS/astat,
	 ASIS/empty-env,
	 ASIS/listlattice,
	 ASIS/portray,
	 ASIS/recursion-parallel,
	 ASIS/unsafe-annot,
	 ASIS/userannot,
	 COMP/builtin-map,
	 COMP/reductions,
	 COMP/rp-alloc,
	 COMP/rp-compiler,
	 COMP/rp-emit,
	 COMP/rp-intrec,
	 COMP/rp-rewrite,
	 COMP/rp-transform,
	 COMP/rp-util,
	 COMP/rp-varclasses,
	 COMP/safeness,
	 COMP/shared-clause,
	 COMP/shared-unify,
	 COMP/types,
	 COMP/unify,
	 POST/inline-opcodes,
	 POST/heaptest,
	 POST/inlineable,
	 POST/luther-emit,
	 POST/peep,
	 POST/regalloc,
	 POST/unsafe,
	 PRE/callgraph,
	 PRE/index,
	 PRE/lift,
	 PRE/load-file,
	 PRE/load-rp-file,
	 PRE/preprocessor,
	 PRE/lift,
	 UTIL/arithmetic,
	 UTIL/basics,
	 UTIL/dict,
	 UTIL/equivclass,
	 UTIL/error,
	 UTIL/expand_clause,
	 UTIL/filename,
	 UTIL/save,
	 UTIL/sets,
	 UTIL/vars]) :-
 ASIS = analysis,
 COMP = compilation,
 POST = postprocess,
 PRE = preprocess,
 UTIL = util.

some_files(
	[COMP/builtin-map,
	 COMP/reductions,
	 COMP/rp-alloc,
	 COMP/rp-compiler,
	 COMP/rp-emit,
	 COMP/rp-intrec,
	 COMP/rp-rewrite,
	 COMP/rp-transform,
	 COMP/rp-util,
	 COMP/rp-varclasses]).
some_other_files([	 COMP/safeness,
	 COMP/shared-clause,
	 COMP/shared-unify,
	 COMP/types,
	 COMP/unify,
	 POST/inline-opcodes,
	 POST/heaptest,
	 POST/inlineable,
	 POST/luther-emit,
	 POST/peep,
	 POST/regalloc,
	 POST/unsafe,
	 PRE/callgraph,
	 PRE/index,
	 PRE/lift,
	 PRE/load-file,
	 PRE/load-rp-file,
	 PRE/preprocessor,
	 UTIL/arithmetic,
	 UTIL/basics,
	 UTIL/dict,
	 UTIL/equivclass,
	 UTIL/error,
	 UTIL/expand_clause,
	 UTIL/filename,
	 UTIL/save,
	 UTIL/sets,
	 UTIL/vars]) :-
 ASIS = analysis,
 COMP = compilation,
 POST = postprocess,
 PRE = preprocess,
 UTIL = util.

comp_iter([],_).
comp_iter([X|Xs],Opts) :-
	( comp(X,Opts) ->
	  true
	; true
	),
	comp_iter(Xs,Opts).
